### ISSUE TITLE
Compilation on Gnu systems fails

### ISSUE THREAD

**Issue by markzyu** [sksullivan/SigSoft-GL-HelloWorld#1]
Tested on Cygwin,

I had to use

``` bash
make DEPS="-lgl -lglu -lglut"
```

to compile the program.

If I remember correctly, the "-framework" commandline option should be Mac-only.

**Comment by markzyu** [comment]
I saw that you just updated the README.md... So I am closing this now.

**Comment by sksullivan** [comment]
No worries man! I just added it in response to your comment, so thanks for pointing it our.

Steve
